---
title: "Stat4911PracticeProject"
author: "Armaan Sodhi.23"
date: "2025-01-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
install.packages("nyfcflights13")
library(nycflights13)
library(ggplot2)
library(dplyr)
library
```

```{r}
airlines <- nycflights13::airlines
airports <- nycflights13::airports
flights <- nycflights13::flights
planes <- nycflights13::planes
weather <- nycflights13::weather
```

```{r}
top10AirportsDest <- flights %>%
  group_by(dest) %>%
  count %>%
  arrange(desc(n)) %>%
  head(10)
```

```{r}
ggplot(top10AirportsDest, aes(x = reorder(dest, -n), y = n)) +
    geom_bar(stat = "identity") +
  labs(title = "Top 10 Airports by Destination",
       x = "Destination Airport",
       y = "Count") +
  theme_minimal()
```

```{r}
AirportOrigin <- flights %>%
  group_by(origin) %>%
  count %>%
  arrange(desc(n)) %>%
  head(10)
```

```{r}
ggplot(AirportOrigin, aes(x = reorder(origin, -n), y = n)) +
    geom_bar(stat = "identity") +
  labs(title = "Top Airports by Origin",
       x = "Origin Airport",
       y = "Count") +
  theme_minimal()
```

```{r}
flights %>%
  group_by(dest) %>%
  count() %>%
  summarise(frequency = n,
            origin) %>%
  arrange(-frequency)

flights <- flights %>%
  drop_na()

weather <- weather %>%
  drop_na()

length(flights)

flights$delay <- TRUE


range(flights$dep_delay)
for (i in 1:nrow(flights)) {
  if (flights$dep_delay[i] >= 15) {
    flights$delay[i] = TRUE}
  else if (flights$dep_delay[i] >= 0 && flights$dep_delay[i] < 15) {
    flights$delay[i] = FALSE
  } else {
    flights$delay[i] = "Early"
  }
  }

flights %>%
  count(delay)

flights$dep_delay

str(flights)
```

```{r plane sizes}

planes$size <- "Small"

for (i in 1:nrow(planes)) {
  if (planes$seats[i] > 25 && planes$seats[i] <= 180) {
    planes$size[i] = "Medium"}
  else if (planes$size[i] > 180) {
    planes$size[i] = "Large"
  }
  }

```

To look at for weather relationship with delay:
  humid
  

  wind_dir
  wind_speed
  precip
  visib

```{r}
weather$time_hour <- as.POSIXct(weather$time_hour, format = "%Y-%m-%d %H:%M:%S")
flights$time_hour <- as.POSIXct(flights$time_hour, format = "%Y-%m-%d %H:%M:%S")

merged <- right_join(flights, weather, by = c("origin", "time_hour"))
view(merged)
```
